site_name: PIP
site_url: https://www.pip.eco/
site_description: Positive Impact Passport
site_author: Scape Foundation
lang: en

repo_name: 'GitHub'
repo_url: https://github.com/scape-foundation/pip/
edit_uri_template: 'docs/{path}'

dev_addr: 127.0.0.1:8888

theme:
  name: material
  locale: en
  palette:
    scheme: scapefoundation
  logo: assets/image/logo_light.png
  favicon: assets/favicon/favicon.ico
  # features:
  #   - navigation.tabs

extra_css:
  - assets/style/extra.css
extra_javascript:
  - assets/script/extra.js
extra_templates:

extra:
  generator: false
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/solid/globe 
      link: https://www.scape.foundation
    - icon: fontawesome/brands/github 
      link: https://github.com/scape-foundation/
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/scape-foundation/
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/scape.foundation/
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/scape.foundation/

copyright: Copyright &copy; 2023 Stichting Scape Foundation

hide:
  - footer

# nav:
#   - Getting Started:
#       - 'Introduction': 'index.md'
#       - 'Quick Start': 'quick_start.md'
#       - 'Template': 'template.md'
#       - 'Fields': 'fields.md'
#   - Glossary: 'glossary.md'
#   - References: 'references.md'
#   - License: 'license.md'
#   - Privacy Policy: 'privacy.md'